import { Share2, Download, Link2, Printer } from 'lucide-react';
import { Comparison } from '../../../types';

interface ExportShareButtonsProps {
  comparison: Comparison;
}

export function ExportShareButtons({ comparison }: ExportShareButtonsProps) {
  const handleCopyLink = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url);
    alert('Comparison link copied to clipboard!');
  };

  const handleShare = async () => {
    const url = window.location.href;
    const title = `${comparison.phone1.brand} ${comparison.phone1.model} vs ${comparison.phone2.brand} ${comparison.phone2.model}`;
    const text = `Compare ${comparison.phone1.brand} ${comparison.phone1.model} and ${comparison.phone2.brand} ${comparison.phone2.model} on MobiMEA Compare`;

    if (navigator.share) {
      try {
        await navigator.share({
          title,
          text,
          url,
        });
      } catch (error) {
        console.log('Share cancelled or failed:', error);
      }
    } else {
      handleCopyLink();
    }
  };

  const handleDownloadJSON = () => {
    const data = JSON.stringify(comparison, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${comparison.phone1.model}_vs_${comparison.phone2.model}_comparison.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadReport = () => {
    const reportContent = `
Phone Comparison Report
=======================

${comparison.phone1.brand} ${comparison.phone1.model} vs ${comparison.phone2.brand} ${comparison.phone2.model}

SUMMARY
-------
${comparison.insights.tldr.summary}

VERDICT
-------
${comparison.insights.tldr.verdict}

KEY DIFFERENCES
--------------
${comparison.insights.highlights.map((h, i) => `
${i + 1}. ${h.title}
   ${h.claim}
   Why it matters: ${h.whyItMatters}
`).join('\n')}

CATEGORY SCORES
---------------
${comparison.insights.categoryScores.map(s => `
${s.category.toUpperCase()}: ${s.phone1Score} vs ${s.phone2Score} (Winner: ${s.winner})
${s.rationale}
`).join('\n')}

PRICING
-------
${comparison.phone1.brand} ${comparison.phone1.model}: ${comparison.phone1.pricing?.[0]?.currency} ${comparison.phone1.pricing?.[0]?.basePrice}
${comparison.phone2.brand} ${comparison.phone2.model}: ${comparison.phone2.pricing?.[0]?.currency} ${comparison.phone2.pricing?.[0]?.basePrice}

---
Report generated by MobiMEA Compare
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${comparison.phone1.model}_vs_${comparison.phone2.model}_report.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm">
      <h3 className="text-xl font-bold text-neutral-900 mb-4">Export & Share</h3>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <button
          onClick={handleShare}
          className="flex flex-col items-center gap-2 p-4 border-2 border-neutral-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all"
        >
          <Share2 size={24} className="text-primary-600" />
          <span className="text-sm font-medium text-neutral-900">Share</span>
        </button>

        <button
          onClick={handleCopyLink}
          className="flex flex-col items-center gap-2 p-4 border-2 border-neutral-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all"
        >
          <Link2 size={24} className="text-primary-600" />
          <span className="text-sm font-medium text-neutral-900">Copy Link</span>
        </button>

        <button
          onClick={handleDownloadReport}
          className="flex flex-col items-center gap-2 p-4 border-2 border-neutral-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all"
        >
          <Download size={24} className="text-primary-600" />
          <span className="text-sm font-medium text-neutral-900">Report</span>
        </button>

        <button
          onClick={handlePrint}
          className="flex flex-col items-center gap-2 p-4 border-2 border-neutral-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all"
        >
          <Printer size={24} className="text-primary-600" />
          <span className="text-sm font-medium text-neutral-900">Print</span>
        </button>
      </div>

      <div className="mt-4">
        <button
          onClick={handleDownloadJSON}
          className="w-full text-sm text-neutral-600 hover:text-primary-600 underline"
        >
          Download comparison data (JSON)
        </button>
      </div>
    </div>
  );
}
